TAE ARMY/accounts/urls.py
# core django
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordChangeView, PasswordChangeDoneView, PasswordResetConfirmView, PasswordResetCompleteView
# project
from .views import register


urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='accounts/login.html',
        redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    path('register/', register, name='register'),
]

TAE ARMY/expense/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.shortcuts import reverse
from django.http import HttpResponseRedirect
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('expense_manager.urls', 'expense_manager'),
                     namespace='expense_manager')),
    re_path(r'^$', lambda r: HttpResponseRedirect(reverse('accounts:login'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

TAE ARMY/accounts/models.py
from django.db import models

# Create your models here.

TAE ARMY/accounts/forms.py
# core django
from django import forms


# user registration form

class UserRegistrationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
    username = forms.CharField(max_length=254)
    email = forms.EmailField(max_length=254)
    password = forms.CharField(widget=forms.PasswordInput, max_length=32)

TAE ARMY/accounts/views.py
# core django
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login
from django import forms


# project
from .forms import UserRegistrationForm

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                u = User.objects.create_user(username, email, password)
                # add to group
                
                expense_manager = Group.objects.get(name='expense_manager')
                expense_manager.user_set.add(u)

                user = authenticate(username=username, password=password)
                login(request, user)
                return redirect('expense_manager:dashboard')
            else:
                raise forms.ValidationError(
                    'username with that email or password already exists')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})

TAE ARMY/accounts/templates/accounts/auth.html
{% extends 'expense/base.html' %} {% load static %}  {% block head %}
<link rel="stylesheet" href="{% static 'css/auth.css' %}"> {% endblock head %} {% block body %}

<div class="container h-100">

    <div class="row h-100">
        <div class="card col-md-12 my-auto">
            <div class="row card-body">
                <div class="col-md-6">
                    <div class="card-title text-center">
                        <strong>
                        {% block heading %}
                            
                        {% endblock heading %}
                            </strong>
                    </div>
                    <div class="text-secondary w-100 text-center">
                        <i>Don't share your passwords</i>
                    </div>
                    <img class="img-fluid" id="expense-img" src="{% static 'images/expense.jpg' %}" alt="Expense Tracker Image">
                </div>
                <div class="col-md-1">
                    <div class="v-line"></div>
                </div>
                <div class="col-md-5">
                    <img class="img-fluid d-block mx-auto" id="expense-logo" src="{% static 'images/expense_logo.jpg' %}" alt="expense logo" width="140" height="140">
                    
                    {% block auth %}
                        
                    {% endblock auth %}
                        
                </div>
            </div>
        </div>
    </div>

</div>



{% endblock body %}

TAE ARMY/accounts/templates/accounts/login.html
{% extends 'accounts/auth.html' %}

{% block title %}
    User Login
{% endblock title %}
    
{% block heading %}
    Login
{% endblock heading %}
    
{% block auth %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.username.errors }} {{ form.username.label_tag }}
        <input type="text" class="form-control" name="{{ form.username.html_name }}" autofocus maxlength="254" required id="{{ form.username.id_for_label }}"> {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password.errors }} {{ form.password.label_tag }}
        <input type="password" class="form-control" name="{{ form.password.html_name }}" required id="{{ form.password.id_for_label }}"> {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-6">
            <a href="{% url 'accounts:register' %}" style="color:#bd19ba">Register</a>
        </div>
        
    </div>
    <button style="margin-top: 25px;background-color:rgb(65,123,251);border:3px solid rgb(42,44,107);color:white" type="submit" class="btn w-25">Submit</button>
    <input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock auth %}

TAE ARMY/accounts/templates/accounts/register.html
{% extends 'accounts/auth.html' %}


{% block title %}
    User Registration
{% endblock title %}
    
{% block heading %}
    Registration
{% endblock heading %}

{% block auth %}

    
<form method="POST">
    {% csrf_token %} {% for field in form %}
    <div class="form-group">
        {{ field.errors }} {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
    {% endfor %}
    <button style="margin-top: 15px;" type="submit" class="btn btn-primary w-25">Submit</button>
    <input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock auth %}